name: Hikvision Doorbell
description: Connect your Hikvision doorbells to Home Assistant
version: '3.0.0'
slug: hikvision_doorbell
url: https://github.com/pergolafabio/Hikvision-Addons/tree/main/hikvision-doorbell
arch:
- amd64
- i386
- aarch64
startup: application
boot: auto
stdin: true
homeassistant_api: true

# Default options when used as an HA add-on
options:
  doorbells:
    - name: null
      ip: null
      username: admin
      password: ""
  system:
    log_level: INFO
    sdk_log_level: NONE

# Schema for the options above
schema:
  doorbells:
    - name: str
      ip: str
      username: str
      password: str
  system:
    log_level: match(^ERROR|WARNING|INFO|DEBUG$)
    sdk_log_level: match(^NONE|ERROR|INFO|DEBUG$)?

# To request MQTT configuration using the supervisor API
services:
  - "mqtt:need"