name: Hikvision Doorbell
description: Connect your Hikvision doorbells to Home Assistant
version: '2.1'
slug: hikvision_sdk
url: https://github.com/pergolafabio/Hikvision-Addons/tree/main/hikvision-sdk
arch:
- amd64
- i386
- aarch64
host_network: true
startup: application
boot: auto
stdin: true
homeassistant_api: true
hassio_api: true

# Default options when used as an HA add-on
options:
  doorbells:
    - name: null
      ip: null
      username: ""
      password: ""
  sensors:
    door: hikvision_door
    callstatus: hikvision_callstatus
    motion: hikvision_motion
    tamper: hikvision_tamper
    dismiss: hikvision_dismiss
  home_assistant:
    url: "http://supervisor/core"
  system:
    log_level: WARNING
    sdk_log_level: NONE

schema:
  doorbells:
    - name: str
      ip: str
      username: str
      password: str
  sensors:
    door: str
    callstatus: str
    motion: str
    tamper: str
    dismiss: str
  home_assistant:
    url: match(^http://supervisor/core$)
  system:
    log_level: match(^ERROR|WARNING|INFO|DEBUG$)
    sdk_log_level: match(^NONE|ERROR|INFO|DEBUG$)?
